CREATE DATABASE cars
USE cars
-- 1) READ DATA--
SELECT * FROM car_dekho

-- 2) TOTAL CARS:TO GET A COUNT OF TOTAL RECORDS--
SELECT count(*) FROM car_dekho

-- 3) THE MANAGERS ASKED THE EMPLOYEE HOW MANY CARS WILL BE AVAILABLE IN YEAR 2023 --
SELECT count(*) FROM car_dekho
WHERE year=2023

-- 4) THE MANAGERS ASKED THE EMPLOYEE HOW MANY CARS AVAILABLE IN YEAR 2020,2021,2022 --
SELECT year,count(*) FROM car_dekho
WHERE year IN (2020,2021,2022)
GROUP BY year

-- 5) TOTAL COUNT OF CARS BY YEAR WITHOUT THE DETAILS --
SELECT year,count(*) FROM car_dekho
GROUP BY year

-- 6) HOW MANY DIESEL CARS IN YEAR 2020 --
SELECT COUNT(*)
FROM car_dekho
WHERE year=2020 AND fuel="Diesel"

-- 7) CLIENT REQUESTED FOR COUNT OF PETROL CARS IN 2020 --
SELECT COUNT(*)
FROM car_dekho
WHERE year=2020 AND fuel="Petrol"

-- 8) PRINT ALL CARS WITH DIFFERENT FUEL BY YEARS --

-- 8a)FOR PETROL CARS --
SELECT year,COUNT(*) as petrol_based 
FROM car_dekho
WHERE fuel="Petrol"
GROUP BY year
-- 8b) FOR DIESEL--
SELECT year,COUNT(*) as DIESEL_BASED 
FROM car_dekho
WHERE fuel="Diesel"
GROUP BY year
-- 8c) FOR CNG --
SELECT year,COUNT(*) as CNG_BASED
FROM car_dekho
WHERE fuel="CNG"
GROUP BY year

-- 9) WHICH YEARS HAD COUNT MORE THAN 100 FOR CARS --
SELECT year,COUNT(*)
FROM car_dekho
GROUP BY year
HAVING COUNT(*)>100

-- 10) COUNT OF CARS BETWEEN YEAR 2015 AND 2023 --
SELECT COUNT(*)
FROM car_dekho
WHERE year BETWEEN 2015 AND 2023

-- 11) PRINT ALL CAR DETAILS BETWEEN YEARS 2015 AND 2023 --
SELECT * 
FROM car_dekho
WHERE year BETWEEN 2015 AND 2023

-- END--